language: ruby
rvm:
  - 2.5

before_install:
  - gem --version
  - gem update --system 3.0.6
  - gem --version
  - bundler -v
  - gem install bundler -v 2.0.2
  - bundler -v
script: "JEKYLL_ENV=production bundle exec jekyll build -d docs/"
