language: ruby
rvm:
  - 2.5.1

before_install:
  - gem --version
  - gem update --system 3.0.6
  - gem --version
  - bundler -v
  - gem install bundler -v 2.0.2
  - bundler -v
script: "JEKYLL_ENV=production bundle exec jekyll build"

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
